### ISSUE TITLE
Doesn't complile with linux-4.11.3

### ISSUE THREAD

**Issue by plusInfinity** [KastB/r8169#4]
make -C /usr/src/linux M=$PWD modules
make[1]: Entering directory '/usr/src/linux-4.11.3-gentoo'
  CC [M]  /home/sasha/Activities/X62/r8169-master/r8169_aspm.o
/home/sasha/Activities/X62/r8169-master/r8169_aspm.c:8112:21: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .ndo_get_stats64 = rtl8169_get_stats64,
                     ^
/home/sasha/Activities/X62/r8169-master/r8169_aspm.c:8112:21: note: (near initialization for ‘rtl_netdev_ops.ndo_get_stats64’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:301: /home/sasha/Activities/X62/r8169-master/r8169_aspm.o] Error 1
make[1]: *** [Makefile:1492: _module_/home/sasha/Activities/X62/r8169-master] Error 2
make[1]: Leaving directory '/usr/src/linux-4.11.3-gentoo'
make: *** [Makefile:5: all] Error 2

**Comment by KastB** [comment]
After merging the patch with 4.12 rc3 this issue should be solved.
However it won't build with older kernel versions anymore.

**Comment by plusInfinity** [comment]
Do you mean that you will update the patch for 4.12 rc3? The patch is not going to mainline kernel, right?

**Comment by KastB** [comment]
Yes, I updated the patch two days ago and it should compile with 4.11 now.
This patch was denied as it causes problems on some hardware configurations and they didn't like the parameter as an opt-in.
